### ISSUE TITLE
components must use css to hide rather than vdom

### ISSUE THREAD

**Issue by shmish111** [purescript-halogen/purescript-halogen#707] opened 2020-10-07 16:10 UTC
This may seem obvious but I wasted a long time realising it, if you have a component and you exclude it in your render function under certain conditions (for example you have tabs and one tab contains a component), when you `query` the slot for it you get back `Nothing`. Weirdly, if this slot contains state (for example in some javascript code) then when you render it again the state is remembered.

I have a site with many tabs, 1 of those tabs has a [Monaco editor](https://microsoft.github.io/monaco-editor/index.html) on it.  
1. select editor tab
2. change the text in the editor
3. switch to another tab
4. query the slot for the editor contents (you get `Nothing`)
5. go back to the editor tab (the text you added is still there)
6. query the slot for the editor contents (you get `Just contents`)

So instead of using a vdom pattern of
```purescript
case view of
  OtherTab -> text "hello"
  EditorTab -> slot _editor whatever
```
I have to use a "hide with css" pattern
```purescript
[ div (selectedTab OtherTab) [text "hello"]
, div (selectedTab EditorTab) [slot _editor whatever]
]
```
I don't know if one is more performant than the other but it is annoying from a programmer point of view, I am forced to render and hide everything if I want to be able to query a component that is hidden.

**Comment by garyb** [comment] 2020-10-07 16:32
This is by design, if we didn't do this it'd result in memory leaks since Halogen would have to hold on to every component ever constructed. 

We could introduce explicit disposal, but that's moving further away from making things declarative, and opens a whole other can of worms in regards to what happens when you dispose of a component that still is in the render tree, etc. There are definitely times where you don't want to lose the state of a component, but in my experience that's less common than the reverse, so it'd result in a lot more annoyance than the current way around. At least in this scenario it's very explicit what is happening, whereas if it just doesn't ever forget things, there's no warning that memory usage will continue to climb indefinitely without manual intervention.

Just curious - but assuming this did work they way you had in mind, where do you envision the Monaco editor being when the component is not included in the render tree? If it's not attached to the DOM, it seems like there's a chance of doing things with it might not work anyway, and if it is attached to the DOM but set to `display: none`, how would Halogen know where to put it when it's not in use?

I'm not really sure what you mean here:

> Weirdly, if this slot contains state (for example in some javascript code) then when you render it again the state is remembered.

Could you explain a bit more? If you're referring to state in 3rd party components, that is probably only working by coincidence, perhaps due to data stored in the DOM itself, or something like that.

**Comment by natefaubion** [comment] 2020-10-07 16:43
> edit: Maybe we could make a different kind of slot, or some flag on the component to determine whether it should persist when out of the render tree. I'd still be a bit hesitant to do so though, it does seem like a potential footgun.

The problem is you really likely do not want to retain an entire tree. For example, there are components that have initialization effects which attach to DOM elements. If you destroy the DOM elements, but retain the component tree, they will be in an inconsistent state if you just render it again. If you retain the DOM tree as well, then that isn't any different than just hiding it with CSS.

I could imagine a sort of serialization API and lifecycle hook. For example, in the component finalizer, you could maybe yield serialized state, and a separate lifecycle hook like the initializer for turning it back into component state, and that state is maintained as long as the parent is kept alive (or is serialized as well).

**Comment by natefaubion** [comment] 2020-10-07 16:54
Also note, you can essentially achieve that already by having some sort of state store in your app's `m`.

**Comment by shmish111** [comment] 2020-10-07 16:55
I mean it all makes sense, the weird bit I mentioned is that in the particular case of Monaco (don't know about others) it is storing the editor contents in memory somehow but I don't know how and even when the editor is apparently removed from the DOM (because I tell halogen not to render it) it seems that the contents of the editor is somehow stored somewhere.

I suppose I just have to chalk it up to Monaco storing it's contents magically somewhere, if it hadn't I would have noticed straight away. Happy to close this now.

**Comment by garyb** [comment] 2020-10-07 18:02
Yeah, that is quite odd! The Ace editor didn't behave this way, so it does seem to be Monaco-specific. I guess if you wanted to get Halogen-consistent behaviour, you'd need to add an initializer to the Monaco-wrapping component that resets the state of the editor or something.

**Closed by garyb** 2020-10-07 18:02 UTC

**Comment by kritzcreek** [comment] 2020-10-07 18:17
Monaco uses Webworkers, the state probably lives somewhere in there.
